### ISSUE TITLE
Simplify TLS setup and migrate config to TOML

### ISSUE THREAD

**Issue by THS-on** [keylime/enhancements#72]
# Enhancement Description
- One-line enhancement description (can be used as a release note): The TLS setup is simplified to two key certificate pairs (client, server) and a list of trusted CAs per component. The `keylime.conf` is migrated to TOML with separation of the  configs for the single components and versioning for future migrations is added.
- Keylime Enhancement Proposal: (link to keylime/enhancements file, if none yet, link to PR)
- Primary contact (assignee): @THS-on 
- Enhancement target (which target equals to which milestone):
  - Alpha release target (x.y)
  - Beta release target (x.y)
  - Stable release target (x.y)

_Please to keep this description up to date._

**Comment by aplanas** [comment]
I still need to read the proposal, so maybe my comments are redundant or plain wrong.  This is a problem that I was thinking a lot since 6.3.0 and I am wondering if there is not a simple solution hidden here.

Every keylime_agent is deployed with  keylime.conf configuration file, only readable by the agent. In this configuration file we should indicate the address of the registrar and the revocation services IIRC, and after 6.3.0 we need to set the mTLS certificate that will validate the connection with those remote services.

One issue that we had is that the tenant can connect to the agent without any verification, and so the mTLS was introduced.

I am wondering (beside the renames), if the general approach should be that when the agent first connect to the registrar, it will send the certificate for mTLS connections if is not already present in the agent configuration file, and then only valid tenant connections will be accepted.

**Comment by THS-on** [comment]
> I am wondering (beside the renames), if the general approach should be that when the agent first connect to the registrar, it will send the certificate for mTLS connections if is not already present in the agent configuration file, and then only valid tenant connections will be accepted.

The issue is that we still need some CA certificate on the agent. Either the one of the registrar or the one used by the verifier or tenant. Currently the the registration process is over HTTP, so we either put the registrar CA cert on the agent and then pull the trusted CAs from the registrar over HTTPS. We could implement a trust on first connection mechanism, but I don't know what the security impact of that is.

**Comment by THS-on** [comment]
In the end we decided to not go with toml on the Python side, but the proposal is completed.
